### PR TITLE
do not print to console but use a print writer

### PR DESCRIPTION
**Pull request by lausdahl**
I would suggest to make a change and use a print writer instead of writing to directly to the console. This way it can easily be processed as a memory string by others. The behaviour should be unchanged in terms of this repo.

Please merge and delete the branch in case you agree

### CODE REVIEW

**Comment by nickbattle** [comment]
OK, I can see why a direct stdout is too specific. But wouldn't it be more natural for toVDM to mimick toString (ie. return a string) and then have a single top-level call somewhere to direct it to a PrintWriter (or wherever you want)? It would probably use a StringWriter internally, of course, but it keeps the parameter list simple.

**Comment by lausdahl** [comment]
Yes I actually just wanted it as a string. It was easier (quicker ) to add the print writer. I assumed the implementation required it since the output stream was used.

**Comment by nickbattle** [comment]
I think it was just laziness on my part to print it directly. I'd be happy to hack in a string generation, if you don't mind waiting a few days?

**Comment by lausdahl** [comment]
Thanks I think that would be the better solution. I just did the current change to make sure I could use it all as I wanted. I not need it before the week after next

**Comment by nickbattle** [comment]
OK, I've just pushed a change onto master (sorry, should have used development, so I merged it into there too!) that changes the toVDM method to be more like toString, except with the indent argument. Internally, uses StringBuilders to create the strings. I've tested it over the complete set of ~700 cross-check repo FMUs and it seems fine.

So we can reject this PR?

**Comment by nickbattle** [comment]
PS. I'll do the same for FMI3 at some point, but my eyes need a rest!!

**Comment by lausdahl** [comment]
Thanks yes just reject it

**Review by nickbattle — COMMENTED** [review]
As discussed, will reject this because it's been implemented a different way.

**Pull request closed without merging**
