### PR TITLE
Repo cleanup

### LINKED ISSUE #13: Component descriptors at custom location instead of standard location src/assembly
The project contains a number of component descriptors located out side the recommended standard location, next to the `pom.xml` files. Is there a good reason to why the  standard location `${project.basedir}/src/assembly` is not used. 

For reference see the assembly plugin: 
* http://maven.apache.org/plugins/maven-assembly-plugin/examples/single/using-components.html
and
* https://maven.apache.org/guides/mini/guide-assemblies.html

### PR DESCRIPTION
**Pull request by lausdahl**
fixes #13 and #14 and cleans up repo making it ready for use by others and allows deployment.

Dependencies are now pulled from: https://overture.au.dk/artifactory/webapp/#/artifacts/browse/tree/General/vdmj so no special stuff with dependencies required just `mvn package` and all is build.

One thing I didn't do was to move the vdm sources under `src/vdm` which probably would be a good place for these instead of in the module root. It makes is difficult to find the module related stuff like `pom.xml`

### CODE REVIEW

**Comment by nickbattle** [comment]
OK, I think I see what you're doing, but it's quite hard to see the new structure given a PR and file rename/diffs! It looks like you've created two top level projects, "fmi2" and "fmi3" (which makes some sense). Within those, the static semantic model is called "vdm-model"? And the dynamic semantic model is "FMIn_API"?

Can you show me the new directory tree somehow, so I can see it more clearly?

Would it perhaps be clearer to call them "static-model" and "dynamic-model"?

The top level "lib" stuff is still there? Can that go?

There's a README at the top level that explains all the sub-projects, so that will need an edit, though that's less important.

**Comment by nickbattle** [comment]
Ah, it's OK, I just had a look at the repo-cleanup branch. Much easier to see the new structure.

I'd prefer static- and dynamic-model names. And perhaps make the tests lower-case names too, like dynamic-modelex and dynamic-cosim?

**Comment by lausdahl** [comment]
I used the named in the pom files for the modules so module folder matches. This makes it a lot easier to related the stuff maven build to the file structure. I did not make any new names but I also think some of the modules could be named in a cleare way (but I havent yet looked at what the code does so didnt want to start renaming stuff)

The lib folder is not there anymore its pulled in through the repository specified in the pom.

ok I didnt look at the readme but if it did not match the maven names then it needs to be updated to match

**Comment by lausdahl** [comment]
Sounds like a good idea. I think the names was a bit confusing.

Can you rename these. Folder + pom artifactid and then the module section in the parent

**Review by nickbattle — COMMENTED** [review]
See earlier comments.

**Comment by nickbattle** [comment]
I can (do the renaming) but it will take a while. Busy today. Does it take long for you to rename?

**Comment by lausdahl** [comment]
No I can do it but need to know which maven modules should have new names so I do it correctly

**Comment by nickbattle** [comment]
OK, so I think the modules are the levels below "fmi2" and "fmi3". We'll rename "vdmmodel" to "static-model" and "FMIn_API" to "dynamic-model". Then "FMIn_API_ModelEx" is "modelex-test", "FMIn_API_CoSim" is "cosim-test" and "FMI2_Tests" is "static-tests". "FMI3_API_Matrix" is "dynamic-matrix". I think that's all :-)

**Comment by lausdahl** [comment]
I renamed these now. Hope it was like you wanted. Is there more stuff that needs to be changed. There seems to be no maven relation to some of the folders. How are they related?

**Comment by nickbattle** [comment]
OK, those renames now look fine.  The (now) dynamic-matrix folder doesn't have a Maven deliverable; is that what you mean? It's just a place for a script that processes a shared Google Docs spreadsheet that lists every FMI3 API and which modes and states it can be called from (with any caveats). The awk script there processes the CSV download from Google and produces VDM that can then be included in the dynamic-model as "the rules" for what can be called when.

**Comment by lausdahl** [comment]
ok. I just want to be sure that none of the stuff not in a maven module is required to use the tool else where.

**Comment by lausdahl** [comment]
What about the version numbers is it intensional that they all differ and have a mix of SNAPSHOT etc. If we could simplify it so all of them are alike then releasing the tool will be as simple as:

~~~~bash
mvn -Dmaven.repo.local=repository release:clean
mvn -Dmaven.repo.local=repository release:prepare -DreleaseVersion=${RELEASE_VER} -DdevelopmentVersion=${NEW_DEV_VER}
mvn -Dmaven.repo.local=repository release:perform
~~~~

**Comment by nickbattle** [comment]
Version numbers have never mattered before. We got a bit confused when releasing VDMCheck2 and VDMCheck3, which are really different tools rather than different versions of the same tool. If it makes things easier to clean that up, I'm perfectly happy.

**Comment by lausdahl** [comment]
ok I made two pull requests towards this branch. If these should go in feel free to press the merge and delete the branches for all 3.

**Pull request merged**
