### PR TITLE
Added artifactory deploy to maven workflow

### PR DESCRIPTION
**Pull request by CThuleHansen**
So this pull-request does the following:
See #18 

All branches and the events: push and pull request will be tested on windows and ubuntu.

Pushes to development will be deployed to artifactory snapshot.

Pushes to master will be deployed to artifactory release.

I am wondering if we should set up the development / master branch structure before we merge this?
If this structure something you want to have @nickbattle ? I do not want to impose something on you :)

### CODE REVIEW

**Review by nickbattle — APPROVED** [review]
OK, not an expert in these things but it looks sensible.

**Comment by nickbattle** [comment]
> I am wondering if we should set up the development / master branch structure before we merge this?
> If this structure something you want to have @nickbattle ? I do not want to impose something on you :)

I haven't really needed different branches as yet, but it's easy to set up a development branch too. I'll do that tomorrow.

**Comment by nickbattle** [comment]
I've just created a development branch.  What are these ctm/* branches for?

**Comment by CThuleHansen** [comment]
I cannot remember the error desc. I Will check it next week. Deploy2 Will be gone once merged

**Comment by CThuleHansen** [comment]
Redoing to development instead.

**Pull request closed without merging**
